version: '3.8'

services:
  app:
    build: .
    container_name: my-node-app
    ports:
      - "3000:3000"  
    environment:
      - NODE_ENV=development  
    volumes:
      - .:/src/app 
    restart: unless-stopped
